# Generated by Django 5.0.6 on 2024-06-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chat_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='members',
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
